version: '3.8'
services:
  # Application
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: development

  # Database
  db:
    image: keinos/sqlite3:latest
    volumes:
      - db_data:/db

  # Sendgrid
  sendgrid:
    build: .
    image: sendgrid-maildev
    hostname: sendgrid-maildev
    environment:
      - SENGRID_API_KEY=""
    container_name: sendgrid-maildev
    ports:
      - 1025:1025
      - 1080:1080
      - 3030:3030

volumes:
  db_data:
